/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function mouseClick(button: string): void

export declare function mouseDown(button: string): void

export declare function mouseScroll(length: number, isVertical: boolean): void

export declare function mouseUp(button: string): void

export declare function moveMouseAbs(x: number, y: number): void

export declare function moveMouseRel(x: number, y: number): void
