/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function moveMouseRel(x: number, y: number): void
export function moveMouseAbs(x: number, y: number): void
export function mouseClick(button: string): void
export function mouseDown(button: string): void
export function mouseUp(button: string): void
export function mouseScroll(length: number, isVertical: boolean): void
