use napi::{Error, Result, Status};
use napi_derive::napi;

/// Every variant of a generated enum carries its own `cfg` predicate, so the
/// same variant list (and the same generated TypeScript type) exists on every
/// platform build. Calling a variant that the current platform's `enigo`
/// build doesn't implement fails at runtime with this error instead of
/// changing the shape of `index.d.ts` per target.
fn unsupported(enum_name: &str, variant: &str) -> Error {
  Error::new(
    Status::GenericFailure,
    format!("{enum_name}::{variant} is not supported on this platform"),
  )
}

/// Declares a fieldless, string-mapped napi enum whose variants mirror an
/// `enigo` enum 1:1, plus a fallible conversion into that `enigo` type and a
/// same-platform support check. `$cfg` is the `cfg` predicate under which the
/// matching `enigo` variant exists; use `all()` for variants present on every
/// platform.
macro_rules! define_enigo_enum {
  ($name:ident, $enigo_ty:path, { $($variant:ident => $cfg:meta),* $(,)? }) => {
    #[napi(string_enum)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum $name {
      $($variant),*
    }

    impl $name {
      pub(crate) fn to_enigo(self) -> Result<$enigo_ty> {
        match self {
          $(
            Self::$variant => {
              #[cfg($cfg)]
              { return Ok(<$enigo_ty>::$variant); }
              #[cfg(not($cfg))]
              { return Err(unsupported(stringify!($name), stringify!($variant))); }
            }
          )*
        }
      }

      pub(crate) fn is_supported(self) -> bool {
        match self {
          $(Self::$variant => cfg!($cfg)),*
        }
      }
    }
  };
}

define_enigo_enum!(MouseButton, enigo::Button, {
    Left => all(),
    Middle => all(),
    Right => all(),
    Back => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Forward => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    ScrollUp => all(),
    ScrollDown => all(),
    ScrollLeft => all(),
    ScrollRight => all(),
});

// Mirrors `enigo::Key` variant-for-variant (excluding the deprecated
// `Command`/`Super`/`Windows` aliases of `Meta`, and the data-carrying
// `Unicode`/`Other` variants, which are exposed separately as
// `Enigo::unicodeKey`/`Enigo::otherKey`/`Enigo::text`).
define_enigo_enum!(Key, enigo::Key, {
    Num0 => target_os = "windows",
    Num1 => target_os = "windows",
    Num2 => target_os = "windows",
    Num3 => target_os = "windows",
    Num4 => target_os = "windows",
    Num5 => target_os = "windows",
    Num6 => target_os = "windows",
    Num7 => target_os = "windows",
    Num8 => target_os = "windows",
    Num9 => target_os = "windows",
    A => target_os = "windows",
    B => target_os = "windows",
    C => target_os = "windows",
    D => target_os = "windows",
    E => target_os = "windows",
    F => target_os = "windows",
    G => target_os = "windows",
    H => target_os = "windows",
    I => target_os = "windows",
    J => target_os = "windows",
    K => target_os = "windows",
    L => target_os = "windows",
    M => target_os = "windows",
    N => target_os = "windows",
    O => target_os = "windows",
    P => target_os = "windows",
    Q => target_os = "windows",
    R => target_os = "windows",
    S => target_os = "windows",
    T => target_os = "windows",
    U => target_os = "windows",
    V => target_os = "windows",
    W => target_os = "windows",
    X => target_os = "windows",
    Y => target_os = "windows",
    Z => target_os = "windows",
    AbntC1 => target_os = "windows",
    AbntC2 => target_os = "windows",
    Accept => target_os = "windows",
    Add => target_os = "windows",
    Alt => all(),
    Apps => target_os = "windows",
    Attn => target_os = "windows",
    Backspace => all(),
    Break => all(unix, not(target_os = "macos")),
    Begin => all(unix, not(target_os = "macos")),
    BrightnessDown => target_os = "macos",
    BrightnessUp => target_os = "macos",
    BrowserBack => target_os = "windows",
    BrowserFavorites => target_os = "windows",
    BrowserForward => target_os = "windows",
    BrowserHome => target_os = "windows",
    BrowserRefresh => target_os = "windows",
    BrowserSearch => target_os = "windows",
    BrowserStop => target_os = "windows",
    Cancel => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    CapsLock => all(),
    Clear => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    ContrastUp => target_os = "macos",
    ContrastDown => target_os = "macos",
    Control => all(),
    Convert => target_os = "windows",
    Crsel => target_os = "windows",
    DBEAlphanumeric => target_os = "windows",
    DBECodeinput => target_os = "windows",
    DBEDetermineString => target_os = "windows",
    DBEEnterDLGConversionMode => target_os = "windows",
    DBEEnterIMEConfigMode => target_os = "windows",
    DBEEnterWordRegisterMode => target_os = "windows",
    DBEFlushString => target_os = "windows",
    DBEHiragana => target_os = "windows",
    DBEKatakana => target_os = "windows",
    DBENoCodepoint => target_os = "windows",
    DBENoRoman => target_os = "windows",
    DBERoman => target_os = "windows",
    DBESBCSChar => target_os = "windows",
    DBESChar => target_os = "windows",
    Decimal => target_os = "windows",
    Delete => all(),
    Divide => target_os = "windows",
    DownArrow => all(),
    Eject => target_os = "macos",
    End => all(),
    Ereof => target_os = "windows",
    Escape => all(),
    Execute => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Exsel => target_os = "windows",
    F1 => all(),
    F2 => all(),
    F3 => all(),
    F4 => all(),
    F5 => all(),
    F6 => all(),
    F7 => all(),
    F8 => all(),
    F9 => all(),
    F10 => all(),
    F11 => all(),
    F12 => all(),
    F13 => all(),
    F14 => all(),
    F15 => all(),
    F16 => all(),
    F17 => all(),
    F18 => all(),
    F19 => all(),
    F20 => all(),
    F21 => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    F22 => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    F23 => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    F24 => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    F25 => all(unix, not(target_os = "macos")),
    F26 => all(unix, not(target_os = "macos")),
    F27 => all(unix, not(target_os = "macos")),
    F28 => all(unix, not(target_os = "macos")),
    F29 => all(unix, not(target_os = "macos")),
    F30 => all(unix, not(target_os = "macos")),
    F31 => all(unix, not(target_os = "macos")),
    F32 => all(unix, not(target_os = "macos")),
    F33 => all(unix, not(target_os = "macos")),
    F34 => all(unix, not(target_os = "macos")),
    F35 => all(unix, not(target_os = "macos")),
    Function => target_os = "macos",
    Final => target_os = "windows",
    Find => all(unix, not(target_os = "macos")),
    GamepadA => target_os = "windows",
    GamepadB => target_os = "windows",
    GamepadDPadDown => target_os = "windows",
    GamepadDPadLeft => target_os = "windows",
    GamepadDPadRight => target_os = "windows",
    GamepadDPadUp => target_os = "windows",
    GamepadLeftShoulder => target_os = "windows",
    GamepadLeftThumbstickButton => target_os = "windows",
    GamepadLeftThumbstickDown => target_os = "windows",
    GamepadLeftThumbstickLeft => target_os = "windows",
    GamepadLeftThumbstickRight => target_os = "windows",
    GamepadLeftThumbstickUp => target_os = "windows",
    GamepadLeftTrigger => target_os = "windows",
    GamepadMenu => target_os = "windows",
    GamepadRightShoulder => target_os = "windows",
    GamepadRightThumbstickButton => target_os = "windows",
    GamepadRightThumbstickDown => target_os = "windows",
    GamepadRightThumbstickLeft => target_os = "windows",
    GamepadRightThumbstickRight => target_os = "windows",
    GamepadRightThumbstickUp => target_os = "windows",
    GamepadRightTrigger => target_os = "windows",
    GamepadView => target_os = "windows",
    GamepadX => target_os = "windows",
    GamepadY => target_os = "windows",
    Hangeul => target_os = "windows",
    Hangul => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Hanja => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Help => all(),
    Home => all(),
    Ico00 => target_os = "windows",
    IcoClear => target_os = "windows",
    IcoHelp => target_os = "windows",
    IlluminationDown => target_os = "macos",
    IlluminationUp => target_os = "macos",
    IlluminationToggle => target_os = "macos",
    IMEOff => target_os = "windows",
    IMEOn => target_os = "windows",
    Insert => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Junja => target_os = "windows",
    Kana => target_os = "windows",
    Kanji => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    LaunchApp1 => target_os = "windows",
    LaunchApp2 => target_os = "windows",
    LaunchMail => target_os = "windows",
    LaunchMediaSelect => target_os = "windows",
    Launchpad => target_os = "macos",
    LaunchPanel => target_os = "macos",
    LButton => target_os = "windows",
    LControl => all(),
    LeftArrow => all(),
    Linefeed => all(unix, not(target_os = "macos")),
    LMenu => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    LShift => all(),
    LWin => target_os = "windows",
    MButton => target_os = "windows",
    MediaFast => target_os = "macos",
    MediaNextTrack => all(),
    MediaPlayPause => all(),
    MediaPrevTrack => all(),
    MediaRewind => target_os = "macos",
    MediaStop => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Meta => all(),
    MissionControl => target_os = "macos",
    ModeChange => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Multiply => target_os = "windows",
    NavigationAccept => target_os = "windows",
    NavigationCancel => target_os = "windows",
    NavigationDown => target_os = "windows",
    NavigationLeft => target_os = "windows",
    NavigationMenu => target_os = "windows",
    NavigationRight => target_os = "windows",
    NavigationUp => target_os = "windows",
    NavigationView => target_os = "windows",
    NoName => target_os = "windows",
    NonConvert => target_os = "windows",
    None => target_os = "windows",
    Numlock => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Numpad0 => target_os = "windows",
    Numpad1 => target_os = "windows",
    Numpad2 => target_os = "windows",
    Numpad3 => target_os = "windows",
    Numpad4 => target_os = "windows",
    Numpad5 => target_os = "windows",
    Numpad6 => target_os = "windows",
    Numpad7 => target_os = "windows",
    Numpad8 => target_os = "windows",
    Numpad9 => target_os = "windows",
    OEM1 => target_os = "windows",
    OEM102 => target_os = "windows",
    OEM2 => target_os = "windows",
    OEM3 => target_os = "windows",
    OEM4 => target_os = "windows",
    OEM5 => target_os = "windows",
    OEM6 => target_os = "windows",
    OEM7 => target_os = "windows",
    OEM8 => target_os = "windows",
    OEMAttn => target_os = "windows",
    OEMAuto => target_os = "windows",
    OEMAx => target_os = "windows",
    OEMBacktab => target_os = "windows",
    OEMClear => target_os = "windows",
    OEMComma => target_os = "windows",
    OEMCopy => target_os = "windows",
    OEMCusel => target_os = "windows",
    OEMEnlw => target_os = "windows",
    OEMFinish => target_os = "windows",
    OEMFJJisho => target_os = "windows",
    OEMFJLoya => target_os = "windows",
    OEMFJMasshou => target_os = "windows",
    OEMFJRoya => target_os = "windows",
    OEMFJTouroku => target_os = "windows",
    OEMJump => target_os = "windows",
    OEMMinus => target_os = "windows",
    OEMNECEqual => target_os = "windows",
    OEMPA1 => target_os = "windows",
    OEMPA2 => target_os = "windows",
    OEMPA3 => target_os = "windows",
    OEMPeriod => target_os = "windows",
    OEMPlus => target_os = "windows",
    OEMReset => target_os = "windows",
    OEMWsctrl => target_os = "windows",
    Option => all(),
    PA1 => target_os = "windows",
    Packet => target_os = "windows",
    PageDown => all(),
    PageUp => all(),
    Pause => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Play => target_os = "windows",
    Power => target_os = "macos",
    Print => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    Processkey => target_os = "windows",
    RButton => target_os = "windows",
    RCommand => target_os = "macos",
    RControl => all(),
    Redo => all(unix, not(target_os = "macos")),
    Return => all(),
    RightArrow => all(),
    RMenu => target_os = "windows",
    ROption => target_os = "macos",
    RShift => all(),
    RWin => target_os = "windows",
    Scroll => target_os = "windows",
    ScrollLock => all(unix, not(target_os = "macos")),
    Select => any(target_os = "windows", all(unix, not(target_os = "macos"))),
    ScriptSwitch => all(unix, not(target_os = "macos")),
    Separator => target_os = "windows",
    Shift => all(),
    ShiftLock => all(unix, not(target_os = "macos")),
    Sleep => target_os = "windows",
    Snapshot => target_os = "windows",
    Space => all(),
    Subtract => target_os = "windows",
    SysReq => all(unix, not(target_os = "macos")),
    Tab => all(),
    Undo => all(unix, not(target_os = "macos")),
    UpArrow => all(),
    VidMirror => target_os = "macos",
    VolumeDown => all(),
    VolumeMute => all(),
    VolumeUp => all(),
    MicMute => all(unix, not(target_os = "macos")),
    XButton1 => target_os = "windows",
    XButton2 => target_os = "windows",
    Zoom => target_os = "windows",
});
